"use client";

import { useEffect, useState } from "react";
import AppShell from "../../components/AppShell";
import Loading from "../../components/Loading";
import PageHeader from "../../components/PageHeader";
import RequireUser from "../../components/RequireUser";
import { apiFetch, APIError } from "../../lib/api";

export default function LinkAccountPage() { return <AppShell><RequireUser><Partners /></RequireUser></AppShell>; }
function Partners() { const [code, setCode] = useState(""); const [input, setInput] = useState(""); const [items, setItems] = useState<any[] | null>(null); const [message, setMessage] = useState(""); useEffect(() => { refresh(); }, []); async function refresh() { const [codeBody, partnerBody] = await Promise.all([apiFetch<{ invitation_code: string }>("/partners/invitation-code"), apiFetch<{ associations: any[] }>("/partners")]); setCode(codeBody.invitation_code); setItems(partnerBody.associations); } async function connect(event: React.FormEvent) { event.preventDefault(); setMessage(""); try { await apiFetch("/partners/connect", { method: "POST", body: JSON.stringify({ invitation_code: input }) }); setMessage("Request sent."); setInput(""); refresh(); } catch (e) { setMessage(e instanceof APIError ? e.message : "Unable to connect"); } } if (!items) return <Loading />; return <><PageHeader eyebrow="Together, with boundaries" title="Partner sharing" description="Invite someone you trust and decide what they can see." /><div className="card-grid"><div className="card"><div className="eyebrow">Your invite code</div><h2>{code}</h2><p className="muted">Share this short-lived code with your support person.</p></div><div className="card"><div className="eyebrow">Join someone</div><form onSubmit={connect}><div className="field"><label>Invitation code</label><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="8-character code" /></div><button className="btn btn-primary">Send request</button></form>{message && <p className="success">{message}</p>}</div></div><div className="card" style={{ marginTop: 18 }}><h3>Connections</h3>{items.length === 0 ? <p className="muted">No connections yet.</p> : <div className="list">{items.map((item) => <div className="list-item" key={item.id}><div><strong>{item.owner?.name || item.member?.name || "Partner"}</strong><div className="muted">{item.relationship} · {item.status}</div></div>{item.status === "pending" && item.owner && <button className="btn btn-secondary" onClick={() => apiFetch(`/partners/${item.id}/accept`, { method: "POST" }).then(refresh)}>Accept</button>}</div>)}</div>}</div></>; }

