"use client";

import { useEffect, useState } from "react";
import AppShell from "../../components/AppShell";
import Loading from "../../components/Loading";
import RequireUser from "../../components/RequireUser";
import { apiFetch } from "../../lib/api";

type Message = { id?: number; role: string; content: string };
export default function ChatbotPage() { return <AppShell><RequireUser><Chat /></RequireUser></AppShell>; }
function Chat() { const [conversations, setConversations] = useState<any[]>([]); const [conversationId, setConversationId] = useState<number>(); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [busy, setBusy] = useState(false); useEffect(() => { apiFetch<{ conversations: any[] }>("/chat/conversations").then((body) => setConversations(body.conversations)); }, []); async function choose(id: number) { const body = await apiFetch<{ conversation: any }>(`/chat/conversations/${id}`); setConversationId(id); setMessages(body.conversation.messages); } async function send(event: React.FormEvent) { event.preventDefault(); if (!text.trim()) return; const outgoing = text; setText(""); setMessages((items) => [...items, { role: "user", content: outgoing }]); setBusy(true); try { const body = await apiFetch<{ assistant: string; conversation_id: number }>("/chat/message", { method: "POST", body: JSON.stringify({ text: outgoing, conversation_id: conversationId || null }) }); setConversationId(body.conversation_id); setMessages((items) => [...items, { role: "assistant", content: body.assistant }]); } finally { setBusy(false); } } return <><div className="page-heading"><div><div className="eyebrow">BabyStar assistant</div><h1>Talk it through</h1><p>Supportive information, gentle prompts, and a reminder to involve your care team.</p></div></div><div className="chat-layout"><aside className="chat-sidebar"><button className="btn btn-primary" style={{ width: "100%", marginBottom: 14 }} onClick={() => { setConversationId(undefined); setMessages([]); }}>New conversation</button>{conversations.map((item) => <button key={item.id} className="list-item" style={{ width: "100%", background: "transparent", border: 0, textAlign: "left" }} onClick={() => choose(item.id)}>{item.title}</button>)}</aside><section className="chat-window"><div className="messages">{messages.length === 0 && <div className="card"><h3>What is on your mind?</h3><p className="muted">Ask about a symptom, meal idea, activity, or how to prepare for a conversation with your clinician.</p></div>}{messages.map((message, index) => <div key={message.id || index} className={`message ${message.role}`}>{message.content}</div>)}</div><form className="chat-input" onSubmit={send}><input value={text} onChange={(e) => setText(e.target.value)} placeholder="Write a message…" disabled={busy} /><button className="btn btn-primary" disabled={busy}>{busy ? "…" : "Send"}</button></form></section></div></>; }

