"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import AppShell from "../../components/AppShell";
import Loading from "../../components/Loading";
import PageHeader from "../../components/PageHeader";
import RequireUser from "../../components/RequireUser";
import { apiFetch, Report } from "../../lib/api";

export default function WeeklyReportPage() { return <AppShell><RequireUser><ReportPage /></RequireUser></AppShell>; }
function ReportPage() { const [report, setReport] = useState<Report | null | undefined>(); useEffect(() => { apiFetch<{ report: Report | null }>("/reports/weekly/current").then((body) => setReport(body.report)); }, []); if (report === undefined) return <Loading />; return <><PageHeader eyebrow="A wider view" title="Weekly report" description="Patterns to notice, not numbers to fear." action={<Link href="/weekly-advice" className="btn btn-primary">Weekly advice</Link>} />{!report ? <div className="card"><h3>Your first report is waiting for a few check-ins.</h3><p>Log how you feel through the week and BabyStar will turn it into a gentle summary.</p><Link href="/health-log" className="btn btn-primary">Start a check-in</Link></div> : <><div className="stats"><div className="stat stat-pink"><span className="stat-label">Pregnancy week</span><strong className="stat-value">{report.week_number}</strong></div><div className="stat stat-lilac"><span className="stat-label">Days logged</span><strong className="stat-value">{report.summary?.days_logged || 0}</strong></div><div className="stat stat-mint"><span className="stat-label">Exercise minutes</span><strong className="stat-value">{report.activities?.total_exercise_minutes || 0}</strong></div><div className="stat"><span className="stat-label">Average sleep</span><strong className="stat-value">{report.activities?.avg_sleep_hours || "—"}</strong></div></div><div className="card-grid"><div className="card"><div className="eyebrow">Highlights</div><h3>{report.summary?.overall_status || "Stable"}</h3><p>{report.summary?.positive_highlights?.join(" ") || "Keep listening to your body and logging what matters."}</p></div><div className="card"><div className="eyebrow">Symptoms</div><h3>{report.summary?.key_symptoms?.length ? report.summary.key_symptoms.join(", ") : "No recurring symptoms"}</h3><p>Patterns are useful context to discuss with your care team.</p></div><div className="card"><div className="eyebrow">Hydration</div><h3>{report.activities?.avg_water_intake_liters || 0} L average</h3><p>{report.activities?.hydration_goal_met ? "You met the gentle 2L goal this week." : "Keep a water bottle nearby and sip regularly."}</p></div></div><div className="card" style={{ marginTop: 18 }}><h3>Daily view</h3><div className="list">{(report.daily_data || []).map((item: any) => <div className="list-item" key={item.date}><strong>{item.date}</strong><span className="muted">{item.exercise_minutes || 0} exercise min · {item.symptom_count || 0} symptoms · {item.sleep || "—"}h sleep</span></div>)}</div></div></>}</>; }

